name: Feature Request for Project Minimalist
description: Propose a new feature or improvement for the Project Minimalist osu! skin.
title: "Feature Request: [Brief Summary]"
labels: ["type: enhancement", "status: under consideration"]
assignees:
  - PopCat19

body:
  - type: markdown
    attributes:
      value: "## 🎨 Feature Proposal for Project Minimalist\nThank you for contributing to the minimalist design of Project Minimalist! Please provide detailed information about your feature proposal below."

  - type: input
    id: feature-title
    attributes:
      label: Feature Title
      description: "Enter a concise title that encapsulates the essence of your feature."
      placeholder: "Title of the proposed feature"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: "What issue does your feature address? Describe the problem that necessitates this feature."
      placeholder: "I find it challenging when..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: "Detail the solution you envision. How does it enhance the minimalist experience?"
      placeholder: "The ideal solution would..."
    validations:
      required: true

  - type: textarea
    id: design-details
    attributes:
      label: Design Details
      description: "Describe any design elements or themes that should be considered for your feature."
      placeholder: "Include color palettes, typography, layout changes, etc..."
    validations:
      required: false

  - type: textarea
    id: alternatives-description
    attributes:
      label: Alternatives Considered
      description: "Have you considered any alternative solutions? Please share them here."
      placeholder: "Other potential solutions include..."
    validations:
      required: false

  - type: checkboxes
    id: skin-impact
    attributes:
      label: Impact on Skin
      description: "Which aspects of the skin do you believe your feature will improve?"
      options:
        - label: Aesthetics
        - label: Usability
        - label: Customization
        - label: Performance
        - label: Other (Please specify in 'Additional Context')
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Provide any additional context, such as screenshots or mockups, that could help illustrate your feature."
      placeholder: "Attach any supplementary materials here..."
    validations:
      required: false

  - type: dropdown
    id: urgency-level
    attributes:
      label: Urgency Level
      description: "How urgent is this feature request for Project Minimalist?"
      options:
        - "Immediate - It's a significant enhancement"
        - "Soon - It's important for the next update"
        - "Eventually - It's a nice-to-have feature"
    validations:
      required: true
