name: Feature Request
description: Propose a new feature or enhancement for this project.
title: "Feature Request: [Please summarize]"
labels: ["type: feature request"]
assignees:
  - PopCat19

body:
  - type: markdown
    attributes:
      value: "## 🚀 Feature Proposal\nPlease fill out the following sections to help us understand your proposal better."

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: "Provide a short and descriptive title for the feature."
      placeholder: "Title of the proposed feature"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: "Describe the problem that this feature would address. Be specific."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: Proposed Solution
      description: "Explain the solution you envision, and how it would benefit users."
      placeholder: "The ideal solution would..."
    validations:
      required: true

  - type: textarea
    id: alternatives-description
    attributes:
      label: Alternatives Considered
      description: "Discuss any alternative solutions or features you've considered."
      placeholder: "Alternative solutions include..."
    validations:
      required: false

  - type: checkboxes
    id: impact
    attributes:
      label: Impact of Feature
      description: "Select the areas that would be impacted by this feature."
      options:
        - label: User Experience
        - label: Performance
        - label: Security
        - label: Other (Please specify in 'Additional Context')
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Provide any additional information or screenshots that might be helpful."
      placeholder: "Additional details, context, or screenshots..."
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency
      description: "How urgent is this feature request?"
      options:
        - "High - It's a blocker"
        - "Medium - It's important but not urgent"
        - "Low - It would be nice to have"
    validations:
      required: true
      
