name: Feature request
description: Suggest an idea for this project
labels: ["Feature Request"]
assignees:
  - PopCat19
body:
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when..."
      placeholder: "Explain the problem you are facing..."
    validations:
      required: true
  - type: textarea
    id: solution-description
    attributes:
      label: Solution Description
      description: "A clear and concise description of what you want to happen."
      placeholder: "Detail the solution you'd like..."
    validations:
      required: true
  - type: textarea
    id: alternatives-description
    attributes:
      label: Alternatives Considered
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "Describe any alternative solutions or features..."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add any additional context or screenshots here..."
    validations:
      required: false
