name: Special request
description: Request for your skin needs. (e.g. custom colors)
title: "[Special]: "
labels: ["Special Request"]
assignees:
  - PopCat19
body:
  - type: input
    id: reason
    attributes:
      label: Reason
      description: "Is your request related to a problem? Please describe."
      placeholder: "I made this request because..."
    validations:
      required: true
  - type: input
    id: describe
    attributes:
      label: Describe
      description: "Describe what you want in your skin."
      placeholder: "I want [...] because [...]"
    validations:
      required: true
  - type: input
    id: alternatives
    attributes:
      label: Alternatives
      description: "Describe alternatives you've considered for the request."
      placeholder: "You can also consider [...] because [...]"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
