---
name: Special request
about: Request for your skin needs. (e.g. custom colors)
title: ''
labels: 'Special Request'
assignees: 'PopCat19'

---

body:
- type: input
  id: reason
  attributes:
    label: Reason
    description: "Is your request related to a problem? Please describe."
    placeholder: "I made this request because..."
  validations:
    required: true

body:
- type: input
  id: describe
  attributes:
    label: Describe
    description: "Describe what you want in your skin."
    placeholder: "I want [...] because [...]"
  validations:
    required: true

body:
- type: input
  id: alternative
  attributes:
    label: Alternatives
    description: "Describe alternatives you've considered for the request."
    placeholder: "You can also consider [...] because [...]"
  validations:
    required: false

body:
- type: input
  id: alternative
  attributes:
    label: Alternatives
    description: "Additional context"
    placeholder: "Add any other context or screenshots about the feature request here."
  validations:
    required: false
