name: Custom Skin Request
description: Submit a request for a customized skin.
title: "[Customization]: " # Please provide a concise title for your request
labels: ["customization"]
assignees:
  - PopCat19

body:
  - type: markdown
    attributes:
      value: |
        ## Customization Request
        Please provide detailed information about your custom skin request.

  - type: textarea
    id: customization
    attributes:
      label: Customization
      description: |
        What kind of customization are you looking for?
      placeholder: |
        Example:
          I need '...' type of customization because '...'
    validations:
      required: true

  - type: textarea
    id: features
    attributes:
      label: Features
      description: |
        What visual features or changes should be incorporated into the skin?
      placeholder: |
        Example:
          I'd like to have '...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: |
        Provide alternatives for redundancy.
      placeholder: |
        Example:
          An alternative could be '...'
    validations:
      required: true

  - type: textarea
    id: visual-preferences
    attributes:
      label: Visual Preferences (optional)
      description: |
        What themes or styles should be incorporated into the skin?
      placeholder: |
        Example:
          I prefer a color scheme of '...' with elements like '...'

  - type: textarea
    id: additional-details
    attributes:
      label: Additional Details (optional)
      description: |
        Provide any other details or context. Attach screenshots or links to visual references if necessary.
      placeholder: |
        Provide any relevant details, references, or attachments.
